### ISSUE TITLE
powershell: first exercise instructions not updated

### ISSUE THREAD

**Issue by sophware** [exercism/powershell#101] opened 2019-01-31 19:02 UTC
The GETTING_STARTED.md file instructions state that the first step in the first powershell exercise is a test suite failure that will report 'hello-world' could not be loaded. It seems that the HelloWorld.ps1 file is not supposed to exist (see next paragraph). Even if it is supposed to exist, what you get is 'Exercise not implemented', just as coded in the script.

The second step says to create a blank file. That file is already there. If the intention is to delete or blank-out the existing file, the instructions can still be corrected to be more clear.

**Comment by iHiD** [comment] 2019-01-31 19:43
I've moved this to the powershell repo (cc @exercism/powershell).

**Comment by masters3d** [comment] 2019-02-27 21:46
@iHiD I am not able to move issues across repos. Should contributors be allowed to more issues to all other repos?

**Comment by masters3d** [comment] 2019-02-27 21:47
Hi @sophware , Do you mind sending a PR to fix this issue the issue you mentioned?

**Comment by sophware** [comment] 2019-03-03 05:03
OK. I did so. It is my first PR; so here's hoping I did it correctly.

Of note, when I run the command to start the exercise (`exercism download --exercise=hello-world --track=powershell`), it doesn't actually download the files in this repository. It downloads similar stuff, but not exactly these files.

**Comment by iHiD** [comment] 2019-03-03 14:29
> I am not able to move issues across repos. Should contributors be allowed to more issues to all other repos?

I don't think it's needed (and I'm not sure how the permissions model for this works). I'm also not sure it's even a publicly available feature on GitHub yet. Regardless, I don't mind doing it :)

**Comment by masters3d** [comment] 2019-03-03 19:10
Okay so I think this is going to be conflicting with https://github.com/exercism/exercism/issues/4707

> There is a stub solution that is missing only the string "Hello, World!"

**Comment by masters3d** [comment] 2019-03-03 21:26
duplicate of https://github.com/exercism/powershell/issues/36

**Closed as completed by masters3d** 2019-03-03 21:26 UTC
